version: "3.9"
services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            -   db
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: "default"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - .:/var/lib/postgresql/data
        ports:
            - "5432:5432"
